# Generated by Django 3.2.5 on 2021-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computershopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='img',
            field=models.ImageField(default='default', upload_to='picture'),
            preserve_default=False,
        ),
    ]
