# Generated by Django 3.2.4 on 2021-07-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computershopapp', '0002_registers_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registers',
            new_name='Task',
        ),
    ]
