# Generated by Django 3.2.5 on 2021-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computershopapp', '0004_auto_20210702_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='picture')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
